//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMGH_MyAttendance.Model
{
    using System;
    
    public partial class attendace
    {
        public int emp_num { get; set; }
        public int acct_num { get; set; }
        public string emp_name { get; set; }
        public Nullable<System.DateTime> att_date { get; set; }
        public string Timetable { get; set; }
        public string clock_in { get; set; }
        public string clock_out { get; set; }
        public string IsAbsent { get; set; }
        public string Department { get; set; }
        public int transaction_id { get; set; }
    }
}
