//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMGH_MyAttendance.Model
{
    using System;
    
    public partial class EmpTimeRecord
    {
        public string emp_name { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string am_in { get; set; }
        public string am_out { get; set; }
        public string pm_in { get; set; }
        public string pm_out { get; set; }
        public Nullable<int> amhours { get; set; }
        public Nullable<int> amMinute { get; set; }
        public Nullable<int> pmHours { get; set; }
        public Nullable<int> pmMinute { get; set; }
        public Nullable<int> UHour { get; set; }
        public Nullable<int> UMin { get; set; }
    }
}
